HelloWorld/src/me/victorhernandez/jsf/HelloBean.java
package me.victorhernandez.jsf;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named("hello")
@SessionScoped
public class HelloBean implements Serializable {
	private String world = "Hello World!";
	
	private String name="";
	

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGretting() {
		if(name.length() == 0) return "";
		else 
			return "Welcome to the jungle: " + name;
	}


	public String getWorld() {
		return world;
	}
	
}

HelloWorld/WebContent/helloBean.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Insert title here</title>
</h:head>
<h:body>
	<h2>#{hello.world}</h2>
	<h:form>
		Enter your Name:
		<h:inputText value="#{hello.name}" />
		<h:commandButton value="Grettings" action="welcome"/>
	</h:form>
</h:body>
</html>

HelloWorld/WebContent/welcome.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>
<title>Welcome</title>
</h:head>
<h:body>
	<h2>#{hello.gretting}</h2>
</h:body>
</html>