HelloJsf/src/main/java/me/victorhernandez/hellojsf/model/Usuario.java
package me.victorhernandez.hellojsf.model;

import java.util.Date;

import javax.validation.constraints.NotNull;

public class Usuario {

	private Long id;
	
    private String username;
	
    private String password;
	
    private String email;
    private Date birthdate;
    
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public Date getBirthdate() {
		return birthdate;
	}
	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}
}

HelloJsf/src/main/java/me/victorhernandez/hellojsf/HelloBean.java
package me.victorhernandez.hellojsf;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@ManagedBean(name="hello")
@RequestScoped
public class HelloBean {
	
	private String greeting = "Hello JSF World!";

	public String getGreeting() {
		return greeting;
	}

	public void setGreeting(String greeting) {
		this.greeting = greeting;
	}
}

HelloJsf/src/main/java/me/victorhernandez/hellojsf/managedbeans/RegisterBean.java
package me.victorhernandez.hellojsf.managedbeans;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import me.victorhernandez.hellojsf.dao.ImplUserDao;
import me.victorhernandez.hellojsf.model.Usuario;


@ManagedBean(name="registrar")
@ViewScoped
public class RegisterBean implements Serializable {

	private static final long serialVersionUID = -1168169122241878645L;
	
	private Usuario user;
	
	public Usuario getUser() {
		return user;
	}

	public RegisterBean(){
		user = new Usuario();
	}
	
	public void submit() {
		addUser(user);
        FacesMessage message = new FacesMessage("Registro exitoso!");
        FacesContext.getCurrentInstance().addMessage(null, message);
        clearForm();
    }
	
	private void clearForm() {
		user.setBirthdate(null);
		user.setEmail("");
		user.setPassword("");
		user.setUsername("");
	}

	private void addUser(Usuario usuario) {
		// obteniendo el contexto
		ApplicationContext ctx = new ClassPathXmlApplicationContext(
				"dao-beans.xml");
		// inyectando el usuario
		ImplUserDao userDao = (ImplUserDao) ctx.getBean("implUserDao");
		userDao.addUser(usuario);
		
	}

}

HelloJsf/src/main/java/me/victorhernandez/hellojsf/managedbeans/RegisteredUsersBean.java
package me.victorhernandez.hellojsf.managedbeans;

import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import me.victorhernandez.hellojsf.dao.ImplUserDao;
import me.victorhernandez.hellojsf.model.Usuario;

@ManagedBean(name = "registrados")
@ViewScoped
public class RegisteredUsersBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5354619065235413950L;

	public List<Usuario> getRegisteredUsers() {
		// obteniendo el contexto
		ApplicationContext ctx = new ClassPathXmlApplicationContext(
				"dao-beans.xml");
		// inyectando el usuario
		ImplUserDao userDao = (ImplUserDao) ctx.getBean("implUserDao");
		//return userDao.getUsuarios();
		return userDao.getAll();

		
	}

	

}

HelloJsf/src/main/webapp/helloBean.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Welcome to JSF 2.0</title>
</h:head>
<h:body>
	<h1>#{hello.greeting}</h1>
</h:body>
</html>

HelloJsf/src/main/webapp/index.jsp
<html>
<body>
<h2>Hello World!</h2>
</body>
</html>

HelloJsf/src/main/webapp/registrar.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<h:outputStylesheet library="css" name="table-style.css" />
	<title>Registrar Usuario</title>
</h:head>
<h:body>
	<h:form id="formulario">
		<h:panelGrid columns="3">
			<h:outputLabel for="username">Nombre del Usuario</h:outputLabel>
			<h:inputText id="username" requiredMessage="Ingrese su usuario"
				label="Usuario" value="#{registrar.user.username}" required="true">
				<f:ajax event="blur" render="usernameMessage" />
			</h:inputText>
			<h:message id="usernameMessage" for="username" />

			<h:outputLabel for="password">Password</h:outputLabel>
			<h:inputSecret id="password" requiredMessage="Ingrese un password"
				label="password" value="#{registrar.user.password}" required="true"
				redisplay="true">
				<f:ajax event="blur" render="passwordMessage" />
			</h:inputSecret>
			<h:message id="passwordMessage" for="password" />

			<h:outputLabel for="email">Email</h:outputLabel>
			<h:inputText id="email" requiredMessage="Favor ingrese un mail"
				label="e-mail" value="#{registrar.user.email}" required="true">
				<f:ajax event="blur" render="emailMessage" />
			</h:inputText>
			<h:message id="emailMessage" for="email" />

			<h:outputLabel for="birthdate">Fecha de Nacimiento (yyyy-MM-dd)</h:outputLabel>
			<h:inputText id="birthdate"
				converterMessage="Ingrese la fecha en formato: yyyy-MM-dd"
				label="birthday" value="#{registrar.user.birthdate}">
				<f:convertDateTime pattern="yyyy-MM-dd" />
				<f:ajax event="blur" render="birthdateMessage" />
			</h:inputText>
			<h:message id="birthdateMessage" for="birthdate" />

			<h:panelGroup />
			<h:commandButton value="Registrar" action="#{registrar.submit}">
				<f:ajax execute="@form" render="@form dataTable" />
			</h:commandButton>
			<h:messages globalOnly="true" layout="table" />
		</h:panelGrid>
		<hr/>
		<h:dataTable id="dataTable" value="#{registrados.registeredUsers}"
			var="c" styleClass="order-table" headerClass="order-table-header"
			rowClasses="order-table-odd-row,order-table-even-row">

			<h:column>
				<f:facet name="header">
    			        Id de Usuario	
    			</f:facet>
    				#{c.id}
    		</h:column>

			<h:column>
				<f:facet name="header">
                                Nombre
				</f:facet>
    				#{c.username}
    		</h:column>

			<h:column>
				<f:facet name="header">
    				Password
				</f:facet>
    				#{c.password}
    		</h:column>

			<h:column>
				<f:facet name="header">
    				e-Mail
				</f:facet>
    				#{c.email}
    		</h:column>
    		
			<h:column>
				<f:facet name="header">
                                Fecha de nacimiento
				</f:facet>
    				#{c.birthdate}
    		</h:column>

		</h:dataTable>
	</h:form>



</h:body>
</html>