SpringHibernate/src/main/java/me/victorhernandez/springhibernate/model/Car.java
package me.victorhernandez.springhibernate.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "CAR_TABLE")
public class Car implements Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="ID")
	private Long id;
	
	@NotEmpty
	@Length(min = 1, max = 30)
	@Column(name="CARNAME")
	private String carName;
	
	@Column(name="PRICE")
	private double price;
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getCarName() {
		return carName;
	}
	public void setCarName(String carName) {
		this.carName = carName;
	}

}

SpringHibernate/src/main/java/me/victorhernandez/springhibernate/managedbean/CarBean.java
package me.victorhernandez.springhibernate.managedbean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;

import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;


import me.victorhernandez.springhibernate.model.Car;
import me.victorhernandez.springhibernate.service.CarService;
import me.victorhernandez.springhibernate.service.CarServiceImp;

@ManagedBean(name="carsMb")
@ViewScoped
public class CarBean implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8382801450376130765L;
	
	@ManagedProperty(value="#{carServiceImp}")
	private CarService service;
	private Car car;
	
	public CarService getService() {
		return service;
	}

	public void setService(CarService service) {
		this.service = service;
	}
	
	
	public CarBean(){
		car = new Car();
	}

	public List<Car> getCars() {
		if(service.getCars() == null)
			return new ArrayList<Car>();
		else
			return service.getCars();
	}
	
	public Car getCar() {
		return this.car;
	}
	public void setCar(Car car) {
		this.car = car;
	}
	
	public void submit(){
		service.addCar(car);
		FacesMessage message = new FacesMessage("Registro exitoso!");
		FacesContext.getCurrentInstance().addMessage(null, message);
	}

}

SpringHibernate/src/main/webapp/done.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<h:outputStylesheet library="css" name="table-style.css" />
	<title>Registrar Usuario</title>
</h:head>
<h:body>
	<h1>Exito!!!</h1>
</h:body>
</html>

SpringHibernate/src/main/webapp/registrar.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<h:outputStylesheet library="css" name="table-style.css" />
	<title>Registrar Vehiculo</title>
</h:head>
<h:body>
	<h:form id="formulario">
		<h:panelGrid columns="3">
			<h:outputLabel for="carname">Marca y Modelo</h:outputLabel>
			<h:inputText id="carname" requiredMessage="Ingrese su vehiculo"
				label="Vehiculo" value="#{carsMb.car.carName}" required="true">
				<f:ajax event="blur" render="carnameMessage" />
			</h:inputText>
			<h:message id="carnameMessage" for="carname" />
			<h:outputLabel for="carprice">Precio del Vehiculo</h:outputLabel>
			<h:inputText id="carprice" requiredMessage="Ingrese un precio"
				label="Precio" value="#{carsMb.car.price}" required="true">
				<f:ajax event="blur" render="carpriceMessage" />
			</h:inputText>
			<h:message id="carpriceMessage" for="carprice" />

			<h:panelGroup />
			<h:commandButton value="Registrar" action="#{carsMb.submit}">
				<f:ajax execute="@form" render="@form dataTable" />
			</h:commandButton>
			<h:messages globalOnly="true" layout="table" />
		</h:panelGrid>
		<hr />
		<h:dataTable id="dataTable" value="#{carsMb.cars}"
			var="c" styleClass="order-table" headerClass="order-table-header"
			rowClasses="order-table-odd-row,order-table-even-row">

			<h:column>
				<f:facet name="header">
    			        Id del Vehiculo	
    			</f:facet>
    				#{c.id}
    		</h:column>

			<h:column>
				<f:facet name="header">
                                Vehiculo
				</f:facet>
    				#{c.carName}
    		</h:column>
			<h:column>
				<f:facet name="header">
                                Precio
				</f:facet>
    				#{c.price}
    		</h:column>
		</h:dataTable>

	</h:form>

</h:body>
</html>